### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by desistefanova** [futureware-tech/simulator-action#249]
**Describe the bug**
We are getting an error in our CI.
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: futureware-tech/simulator-action`

**Additional context**
Could you please update [action.yml](https://github.com/futureware-tech/simulator-action/blob/main/action.yml) to use Node 16?

`runs: using: 'node16'`

**Comment by dotdoom** [comment]
Thank you.  This has been fixed; please used `@v2` version in the `action` clause (see README.md).
