### ISSUE TITLE
Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding

### ISSUE THREAD

**Issue by bartekpacia** [futureware-tech/simulator-action#301]
See [this workflow run](https://github.com/leancodepl/patrol/actions/runs/3913890614/jobs/6690316867).

```
Run futureware-tech/simulator-action@v2
$ xcrun simctl list --json devices available
17 runtimes found
Picked a device: iPhone 14 (iOS 16.0) [E67DAAAB-AF35-4922-9CA6-04030A5566FA] - Shutdown
Erasing device...
$ xcrun simctl erase E67DAAAB-AF35-4922-9CA6-04030A5566FA
Booting device.
$ xcrun simctl boot E67DAAAB-AF35-4922-9CA6-04030A5566FA
Error: Command failed: xcrun simctl boot E67DAAAB-AF35-4922-9CA6-04030A5566FA
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
Unable to boot the Simulator.
launchd failed to respond.
Underlying error (domain=com.apple.SimLaunchHostService.RequestError, code=4):
	Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding

```

It was working fine, and then it wasn't.

**Comment by dotdoom** [comment]
Interesting.  I’ll try to reproduce this tomorrow to get detailed logs.  I was expecting https://github.com/actions/runner-images/issues/6746 to be related, but it has been pushed back a week last minute.

**Comment by bartekpacia** [comment]
Thanks for the fast response. I appreciate a lot the work you've put into this action :)

And good luck trying to reproduce it, although that seems to me like a "random" issue, I hope I'm wrong.

**Comment by dotdoom** [comment]
I couldn't reproduce it.  The evidence on the interwebs shows that it might happen with Xcode 11.3:

https://developer.apple.com/documentation/xcode-release-notes/xcode-11_3-release-notes

> Under certain network conditions, GateKeeper may block simulators from booting, and show error code 60 "launchd failed to respond.” (55878667)

and we have both "code=60" and "launchd failed to respond" error messages here. So eventually, with Xcode update this intermittent problem should be gone.

Unfortunately I failed to capture xcode version information from the logs of that run, and the logs have already expired.
