### ISSUE TITLE
Add support for `macos-13`

### ISSUE THREAD

**Issue by nilsreichardt** [futureware-tech/simulator-action#327]
Since today you can use `macos-13` for GitHub Actions: https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/

Currently, you get this error:

```
Run futureware-tech/simulator-action@ae8f725abebda0c4c62629c7a2a5b826e161c9f1
$ xcrun simctl list --json devices available
7 runtimes found
Error: No devices found for the matching requirements. See https://github.com/futureware-tech/simulator-action/wiki for the list of available devices
```

See https://github.com/SharezoneApp/sharezone-app/actions/runs/4798155440/jobs/8536060696?pr=627

Also see the wiki says that there is no support for `macos-13`: https://github.com/futureware-tech/simulator-action/wiki

**Comment by dotdoom** [comment]
Looking at the workflow, I see the requirement being configured for `iPhone 13` model:

https://github.com/SharezoneApp/sharezone-app/blob/00d36a66e88fde6c8eb6a9d1fdaf765ad2039c1a/.github/workflows/integration_tests_app_ci.yml#L191-L194

When I do print-devices on my Mac with OSX 13, it's indeed not available:

```
$ xcrun simctl list devices available
== Devices ==
-- iOS 16.4 --
    iPhone SE (3rd generation) (A12ECD83-CCC0-4039-B92A-757F0A6093CC) (Shutdown) 
    iPhone 14 (2C0A83BD-0234-43D7-A64B-7417D7B61DC3) (Shutdown) 
    iPhone 14 Plus (F5F1C11E-79F5-4410-A72B-411E43A9E66A) (Shutdown) 
    iPhone 14 Pro (72BDEBEF-FF65-49B7-A0EF-A228413AA779) (Shutdown) 
    iPhone 14 Pro Max (2489433F-6DC8-4BE5-A198-6F068B1AEB19) (Shutdown) 
    iPad Air (5th generation) (9D31D868-00BB-44DE-ACC9-2B9A5A018468) (Shutdown) 
    iPad (10th generation) (F01173A0-C306-4609-A391-D3BD05E0B6E1) (Shutdown) 
    iPad mini (6th generation) (A5EB8BD0-E18A-4714-8A5E-CD7E9173D4C0) (Shutdown) 
    iPad Pro (11-inch) (4th generation) (5574DE0C-FCE5-49B8-91C6-70088BE8F68C) (Shutdown) 
    iPad Pro (12.9-inch) (6th generation) (3152A458-03D4-4736-A1F0-790FB852876A) (Shutdown) 
```

So the solution would be to either change your model requirement to `iPhone 14`, or wait for #291 to be resolved.

Meanwhile updated the print-devices workflow to include `macos-13`, and the device list should be available within 12hours on Wiki.  Thanks for pointing this out.

**Comment by dotdoom** [comment]
Great!

`macos-13` device list is now available in [wiki](https://github.com/futureware-tech/simulator-action/wiki/Devices-macos-13)
